language: generic
sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7ded9eef8e2ac2055abf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
    global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1366"
    matrix:
    - DM_MAPFILE="metastation"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh 
  - ./install-byond.sh

script:
  - (! grep 'step_[xy]' _maps/**/*.dmm)
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
